PcStoreWebsite/Models/ContactUs.cs
namespace PcStoreWebsite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    
    public partial class ContactUs
    {
        [Key]
        [Column(Order = 0)]
        [StringLength(50)]
        public string UserId { get; set; }

        [Key]
        [Column(Order = 1)]
        [StringLength(90)]
        public string Message { get; set; }

        public virtual Login Login { get; set; }
    }
}

PcStoreWebsite/Models/Login.cs
namespace PcStoreWebsite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Login")]
    public partial class Login
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public Login()
        //{
        //    ContactUs = new HashSet<ContactUs>();
        //    Orders = new HashSet<Orders>();
       // }

        [Key]
        [StringLength(50)]
        public string UserId { get; set; }

        [Required]
        [StringLength(500)]
        public string UserPass { get; set; }

        [StringLength(50)]
        public string Email { get; set; }

        [StringLength(50)]
        public string Credits { get; set; }

        public bool Flag { get; set; }

        [Required]
        [StringLength(50)]
        public string Catagory { get; set; }

        public bool isAdmin { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<ContactUs> ContactUs { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<Orders> Orders { get; set; }
    }
}

PcStoreWebsite/Controllers/CBLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PcStoreWebsite.Models;
using System.Threading;

namespace PcStoreWebsite.Controllers
{
    public class CBLoginController : Controller
    {
       
        public ActionResult ViewMyOrders()
        {
            if (Session["UserId"] == null)
            {
                return View("Login");
            }
            var MyID = Session["UserId"].ToString();
            //Now we make the user login automaticlly login in after registartion.
            using (DBConnection db = new DBConnection())
            {
                var usr = db.Orders.Where(u => u.UserId == MyID).FirstOrDefault();
                var MyUserId = Session["UserId"].ToString();
                //if we found orders for the user
                if (Session["UserId"] != null)
                {
                    //List<Orders> myOrder = (from x in db.Orders where MyID == usr.UserId.ToString() select x).ToList<Orders>();
                    //List<Products> Product = (from x in db.Products select x).ToList<Products>();
                    List<Products> myProducts = (from x in db.Products join y in db.Orders on MyUserId equals y.UserId where (x.ProductId == y.ProductId) && (MyUserId == y.UserId) select x).ToList<Products>();
                    //List<Products> myRealProducts;
                    //for(int i=0;i<myOrder.Count;i++)
                    //{
                    //    myRealProducts.Add
                    //}

                    return View(myProducts.ToList());

                }
                else
                {
                    //There are no orders.
                    return View();
                }
            }
        }
        public ActionResult Test()
        {
            return View();
        }
        
        public ActionResult Registration()
        {
            return View();
        }
    
        [HttpPost]
        public ActionResult Registration(Login User)
        {
            Encryption enc = new Encryption();
            //Save to Data Base
            if (User.Email == null)
            {
                User.Email = "";
            }
            if (User.Catagory == null)
            {
                User.Catagory = "Other";
            }
            if (User.UserPass == null)
            {
                return RedirectToAction("Registration");
            }
            if (User.Credits == null)
            {
                User.Credits = "10000";
            }
            if (ModelState.IsValid)
            {
                string hashedPassword = enc.CreateHash(User.UserPass);
                User.UserPass = hashedPassword;

                using (DBConnection db = new DBConnection())
                {
                    db.Login.Add(User);
                    db.SaveChanges();
                }
                ModelState.Clear();
                //ViewBag.Message = User.UserId + "" + "Successfully Registered!";    
            }


            //Now we make the user login automaticlly login in after registartion.
            using (DBConnection db = new DBConnection())
            {

                var usr = db.Login.Where(u => u.UserId == User.UserId && u.UserPass == User.UserPass).FirstOrDefault();
                if (usr != null)
                {
                    Session["UserId"] = usr.UserId.ToString();
                    Session["UserPass"] = usr.UserPass.ToString();
                    Session["isAdmin"] = usr.isAdmin.ToString();
                    Session["Email"] = usr.Email.ToString();
                    Session["Catagory"] = usr.Catagory.ToString();                    
                    Session["Credits"] = usr.Credits.ToString();
                    Session["Flag"] = usr.Flag.ToString();
                    return RedirectToAction("LoggedIn");
                }
                else
                {
                    ModelState.AddModelError("", "ERROR: Username or password are not correct.");
                }
            }

            return View("LoggedIn");
        }
        public ActionResult ViewTableIndex()
        {
            Thread.Sleep(4000);
            if (Session["UserId"] != null)
            {
                if (Session["isAdmin"].ToString().Equals("True"))
                {
                    using (DBConnection db = new DBConnection())
                    {
                        return Json(db.Login.ToList(), JsonRequestBehavior.AllowGet);
                    }
                }
                ViewBag.ErrorMessage = "You are not an Admin.";
                return View("Login");
            }
            return View("Login");

        }


        public ActionResult Index()
        {

            if (Session["UserId"] != null)
            {
                if (Session["isAdmin"].ToString().Equals("True"))
                {
                    using (DBConnection db = new DBConnection())
                    {
                        return View(db.Login.ToList());
                        //return Json(db.Login.ToList(), JsonRequestBehavior.AllowGet);
                        //return View(db.Login.ToList());
                    }
                }
                ViewBag.ErrorMessage = "You are not an Admin.";
                return View("Login");

            }
            else
            {
                ViewBag.ErrorMessage = "You are not an Admin.";
                return View("Login");
            }
        }



        public ActionResult Logout()
        {
            Session.Clear();
            Session.Abandon();
            return View();
        }
        // GET: CBLogin
        public ActionResult Login()
        {

            //if user already logged in
            if (Session["UserId"] != null)
            {
                return RedirectToAction("LoggedIn");
            }
            return View();
        }


        [HttpPost]
        public ActionResult Login(Login user)
        {

            Encryption enc = new Encryption();
            using (DBConnection db = new DBConnection())
            {
                   
                //var usr = db.Login.Where(u => u.UserId == user.UserId && u.UserPass == user.UserPass).FirstOrDefault();
                var usr = db.Login.Where(u => u.UserId == user.UserId).FirstOrDefault();
                if (usr != null)
                {
                    if (enc.ValidatePassword(user.UserPass, usr.UserPass))
                    {
                        Session["UserId"] = usr.UserId.ToString();
                        Session["UserPass"] = usr.UserPass.ToString();
                        Session["isAdmin"] = usr.isAdmin.ToString();
                        Session["Email"] = usr.Email.ToString();
                        Session["Credits"] = usr.Credits.ToString();
                        Session["Catagory"] = usr.Catagory.ToString();
                        Session["Flag"] = usr.Flag.ToString();
                        return RedirectToAction("LoggedIn");
                    }
                    else
                    {
                        ModelState.AddModelError("", "ERROR: Username or password are not correct.");
                    }
                }
                
            }
            return View();

        }
        public ActionResult MyProfile()
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login");
            }
            else
            {
                
                return View();
            }
        }

        
        
        //after Update
        [HttpPost]
        public ActionResult MyProfile(Login Usr)
        {
            //Save to Data Base
            if (ModelState.IsValid)
            {
                using (DBConnection db = new DBConnection())
                {
                    //The Default values

                    Usr.UserId = Session["UserId"].ToString();
                    Usr.Credits = Session["Credits"].ToString();
                    Usr.isAdmin = Convert.ToBoolean(Session["isAdmin"]);
                    Usr.Flag = Convert.ToBoolean(Session["Flag"]);
                    var current = Session["UserId"].ToString();
                    //Login usr = (from x in db.Login where x.UserId == Usr.UserId select x).ToList<Login>();
                    var usr = db.Login.Where(u => u.UserId == current).FirstOrDefault();
                    
                    //Remove Old one from data base
                    db.Login.Remove(usr);
                    //Update now
                    db.Login.Add(Usr);
                    db.SaveChanges();
                }
                ModelState.Clear();
                //ViewBag.Message = User.UserId + "" + "Successfully Registered!";    
            }
            if (Session["UserId"] == null)
                {
                    return RedirectToAction("Login");
                }
                else
                {
                return RedirectToAction("Logout");
            }
        }

     
        /// <summary>
        /// saving the user details
        /// </summary>
        /// <returns></returns>
        public ActionResult ContactUs()
        {
            if (Session["UserId"] == null)
            {
                return View("Login");
            }
            return View();
        }
        [HttpPost]
        public ActionResult ContactUs(ContactUs cus)
        {
            
            if(Session["UserId"]==null)
            {
                return View("Login");
            }

            //Save to Data Base
            if (ModelState.IsValid)
            {
                using (DBConnection db = new DBConnection())
                {
                    db.ContactUs.Add(cus);
                    db.SaveChanges();
                }
                ModelState.Clear();
            }
            return View();
        }


        //here we present the products to the user.

PcStoreWebsite/Views/CBLogin/AlreadyPaid.cshtml
@{
    ViewBag.Title = "AlreadyPaid";
    Layout = "~/Views/Shared/_PcStoreLayout.cshtml";
}

<h2>@Session["UserId"], it seem's that you already paid this item,
    thus we could not make this offer :( </h2>

PcStoreWebsite/Views/CBLogin/BuyItem.cshtml
@model PcStoreWebsite.Models.Products

@{
    ViewBag.Title = "BuyItem";
    Layout = "~/Views/Shared/_PcStoreLayout.cshtml";
}



<h2>BuyItem</h2>
@*
<p>
    @Html.ActionLink("Create New", "Create")
</p>*@

<input type="image" src="~/Content/electronix/images/laptop.gif" class="search_bt" />
<html>
<body>

    @using (Html.BeginForm("BuyItem", "CBLogin", FormMethod.Post))
    {
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ProductName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Speed)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RAM)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HardDisk)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Core)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Category)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Warrently)
                </th>
                <th></th>
            </tr>
            @*I'v added this box's to save the values when backing to Controller and update the new credits*@
            @Html.TextBoxFor(m => m.ProductId)
            @Html.TextBoxFor(m=>m.Price)

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => Model.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.Speed)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.RAM)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.HardDisk)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.Core)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.Category)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.Warrently)
                </td>
                @*
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id=item.ProductId }) |
                        @Html.ActionLink("Details", "Details", new { id=item.ProductId }) |
                        @Html.ActionLink("Delete", "Delete", new { id=item.ProductId })
                    </td>

                *@
            </tr>
            
        </table>

        <br />
        <br />
        if (Convert.ToInt32(Session["Credits"].ToString()) >= Model.Price)
        {
            <p><button style="color:green;">Buy Now</button></p>
        }
        else
        {
            <button style="color:red" disabled>Buy Now</button>
        }

    }
</body>
</html>

PcStoreWebsite/Views/CBLogin/ContactUs.cshtml
@model PcStoreWebsite.Models.ContactUs

@{
    Layout = "~/Views/Shared/_PcStoreLayout.cshtml";

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ContactUs</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <div style="font-size:30px; text-align:center; color:crimson;">ContactUs</div>
            <div style="font-size:17px;color:blueviolet; text-align:center;">Please fill the fields and press Send button, we will back to you as soon as possible!</div>
            <hr />
            <div style="text-align:center;">
                @Html.ValidationSummary(true)
                <div class="form-group">
                    @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">

                        @* @Html.DropDownList("UserId", String.Empty)*@
                        @Html.EditorFor(model => model.UserId)
                        @Html.ValidationMessageFor(model => model.UserId)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Message)
                        @Html.ValidationMessageFor(model => model.Message)
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Send" style="font-size:20px;" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </div>
    }
    
</body>
</html>

PcStoreWebsite/Views/CBLogin/Index.cshtml
@model IEnumerable<PcStoreWebsite.Models.Login>

@{
    Layout = null;
    Layout = "~/Views/Shared/_PcStoreLayout.cshtml";

}
<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>

<!DOCTYPE html>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<html>
<head>

    <meta name="viewport" content="width=device-width" />
    <title>Index</title>


    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }
        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }
        tr:nth-child(even) {
            background-color: #dddddd;
        }
        body {
            padding: 20px 20px;
        }

        .results tr[visible='false'],
        .no-result {
            display: none;
        }

        .results tr[visible='true'] {
            display: table-row;
        }

        .counter {
            padding: 8px;
            color: #ccc;
        }
    </style>




</head>


<body>


    <div class="form-group pull-right">
        <input type="text" class="search form-control" placeholder="What are you looking for?">
    </div>
    <p>

        <br />

        <br />
        <h2 style="color:cyan; font-size:18px;">Here all the list of the available Users :-</h2>
        <br />
    </p>
    <span class="counter pull-right"></span>


    <!--Here we have the table ,note that we loading it via Ajax, so here we just declare the body of table.-->
    <table class="table table-hover table-bordered results" >
        <tr class="warning no-result">
            <td colspan="7"><i class="fa fa-warning" style="color:red;font-size:20px;"></i> No result</td>
        </tr>

    </table>
    <div id="Status">
        <div style="font-size:16px;color:blueviolet;text-align:left;">Loading... Please wait.</div>
        <div style="text-align: center;" class="left_footer"> <img src="~/Content/electronix/images/loading.gif" alt="" width="300" height="200" /> </div>
    </div>

</body>
</html>


@**
    @{
    WebGrid obj = new WebGrid(Model,canSort:true,canPage:true,rowsPerPage:4,ajaxUpdateContainerId:"tblGrid");
    }
*@

<script language="javascript" style="width:100%">

    $(document).ready(function () {
        $(".search").keyup(function () {
            var searchTerm = $(".search").val();
            var listItem = $('.results tbody').children('tr');
            var searchSplit = searchTerm.replace(/ /g, "'):containsi('")

            $.extend($.expr[':'], {
                'containsi': function (elem, i, match, array) {
                    return (elem.textContent || elem.innerText || '').toLowerCase().indexOf((match[3] || "").toLowerCase()) >= 0;
                }
            });

            $(".results tbody tr").not(":containsi('" + searchSplit + "')").each(function (e) {
                $(this).attr('visible', 'false');
            });

            $(".results tbody tr:containsi('" + searchSplit + "')").each(function (e) {
                $(this).attr('visible', 'true');
            });

            var jobCount = $('.results tbody tr[visible="true"]').length;
            $('.counter').text(jobCount + ' item');

            if (jobCount == '0') { $('.no-result').show(); }
            else { $('.no-result').hide(); }
        });
    });
</script>



 <script language="javascript" style="width:100%">
    $("#Status").show();
    $.get("ViewTableIndex", null, BindData);

    function BindData(Model) {

        var tbl = $(".results");
        var flag;
        for (k = 0; k < Model.length; k++) {
            if (Model[k].Flag == true) {
                flag = "Deleted.";
            }
            else {
                flag = " Available.";
            }

            if (k == 0) {
                var newRow =
                    "<thead>" + "<tr>" +


                    "<th>" + "Username" + "</th>" +
                    "<th>" + "Password" + "</th>" +
                    "<th>" + "Email" + "</th>" +
                    "<th>" + "Credits" + "</th>" +
                    "<th>" + "Category" + "</th>" +
                    "<th>" + "is Admin" + "</th>" +
                    "<th>" + "Status" + "</th>" +

                    "</tr>" + "</thead>"




                    + "<tbody>" +
                    "<tr>" +
                    "<td>" + Model[k].UserId + "</td>" +
                    "<td>" + "Hashed." + "</td>" +
                    "<td>" + Model[k].Email + "</td>" +
                    "<td>" + Model[k].Credits + "</td>" +
                    "<td>" + Model[k].Catagory + "</td>" +
                    "<td>" + Model[k].isAdmin  + "</td>" +
                    "<td>" + flag + "</td>" +
                    "</tr>" +
                    "</tbody>"
            }
            else if (k == Model.length - 1)
            {
                var newRow =
                   
                    "<tr>" +
                    "<td>" + Model[k].UserId + "</td>" +
                    "<td>" + "Hashed." + "</td>" +
                    "<td>" + Model[k].Email + "</td>" +
                    "<td>" + Model[k].Credits + "</td>" +
                    "<td>" + Model[k].Catagory + "</td>" +
                    "<td>" + Model[k].isAdmin + "</td>" +
                    "<td>" + flag + "</td>" +
                    "</tr>" 
                    "</tbody>"
            }
            else {
                var newRow =

                    "<tr>" +
                    "<td>" + Model[k].UserId + "</td>" +
                    "<td>" + "Hashed." + "</td>" +
                    "<td>" + Model[k].Email + "</td>" +
                    "<td>" + Model[k].Credits + "</td>" +
                    "<td>" + Model[k].Catagory + "</td>" +
                    "<td>" + Model[k].isAdmin + "</td>" +
                    "<td>" + flag + "</td>" +
                    "</tr>" 
            }
            tbl.append(newRow);

        }
        $("#Status").text("");

    }

</script>

PcStoreWebsite/Views/CBLogin/LoggedIn.cshtml
@model IEnumerable<PcStoreWebsite.Models.Products>

@using System.Threading;

@{
    ViewBag.Title = "LoggedIn";
    Layout = "~/Views/Shared/_PcStoreLayout.cshtml";
}





<!DOCTYPE html>

<html>
<head>

    <meta name="viewport" content="width=device-width" />
    <title>Index</title>


    <style>
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
        }
    </style>
</head>


<body>


    @*If the user at programming catagory.*@
    @if (Session["Catagory"]!=null && Session["Catagory"].ToString().Equals("Programming"))
    {
        <h2 style="text-align:center;color:aqua;">Programmer Products</h2>
        foreach (var item in Model)
        {
            if (item.Category.ToString().Equals("Programming"))
            {
                @*Here you have to add a dynamic things.*@

                    int oldprice = item.Price + 400;
                    <div class="prod_box">

                    <div class="top_prod_box"></div>
                    <div class="center_prod_box">

                        
                        @*
        <div class="product_title"><a href="details.html">@item.ProductName</a></div>
        <div class="product_img"><a href="details.html"><img src="~/Content/electronix/images/laptop.gif" alt="" border="0" /></a></div>

                        *@
                    <div class="product_title">@item.ProductName</div>
                    <div class="product_img"><img src="~/Content/electronix/images/laptop.gif" alt="" border="0" /></div>

                        
                       @Html.ActionLink("Buy Now", "BuyItem", "CBLogin", new { id=@item.ProductId},null)

                        
                    <div style="font:bold;" class="prod_price"><span class="reduce">@oldprice ₪</span> <span class="price">@item.Price ₪ <br />Product ID: @item.ProductId</span></div>
                        </div>
                        </div>

            }
        }
    }

     @*If the user at other catagory.*@

    else if (Session["Catagory"] != null && Session["Catagory"].ToString().Equals("Other"))
    {
        <h2 style="text-align:center;color:aqua;">Other Products</h2>
        foreach (var item in Model)
        {
            if (item.Category.ToString().Equals("Other"))
            {
                @*Here you have to add a dynamic things.*@

    int oldprice = item.Price + 400;
    <div class="prod_box">

        <div class="top_prod_box"></div>
        <div class="center_prod_box">
            <div class="product_title"><a href="details.html">@item.ProductName</a></div>
            <div class="product_img"><a href="details.html"><img src="~/Content/electronix/images/laptop.gif" alt="" border="0" /></a></div>
           
            @Html.ActionLink("Buy Now", "BuyItem", "CBLogin", new { id = @item.ProductId }, null)


            <div style="font:bold;" class="prod_price"><span class="reduce">@oldprice ₪</span> <span class="price">@item.Price ₪<br />Product ID: @item.ProductId</span></div>
        </div>
    </div>

            }
        }
    }
                            @*If the user at unknown catagory.*@
    else
    {
        <h2 style="color:red;">There are no available products for you'r specification.</h2>
    }



</body>
</html>

PcStoreWebsite/Views/CBLogin/Logout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Logout</title>
</head>
<body>


    You have been successfully Logged out !

    @Html.ActionLink("Login Now", "Login");
    <div> 
    </div>
</body>
</html>

PcStoreWebsite/Views/CBLogin/MyProfile.cshtml
@model PcStoreWebsite.Models.Login

@{
    ViewBag.Title = "My Profile";
    Layout = "~/Views/Shared/_PcStoreLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .card {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            max-width: 300px;
            margin: auto;
            text-align: center;
            font-family: arial;
        }

        .title {
            color: grey;
            font-size: 18px;
        }

        button {
            border: none;
            outline: 0;
            display: inline-block;
            padding: 8px;
            color: white;
            background-color: #000;
            text-align: center;
            cursor: pointer;
            width: 100%;
            font-size: 18px;
        }

        a {
            text-decoration: none;
            color: black;
        }

            button:hover, a:hover {
                opacity: 0.7;
            }
    </style>
</head>
<body>
    @using (Html.BeginForm("MyProfile", "CBLogin", FormMethod.Post))
    {
    @*here we make the Ability to user to edit profile.*@
    <div style="font-size:25px;color:blue;text-align:center;">Here you can edit the profile<br /> when you finish press Save button.</div> <br />
    <div style="text-align:center;font-size:20px;">
        <br />
        Password
        <br />
        @Html.TextBoxFor(m=>m.UserPass) @Html.ValidationMessageFor(m=>m.UserPass)
        <br />
       <!--  <input id="Pass" type="text" />-->
        Email
        <br />
        @Html.TextBoxFor(m => m.Email) @Html.ValidationMessageFor(m => m.Email)
        <br />
        
       <!--  <input id="Email" type="text" />
        <br />Category<br />
        <select id="Category">
            <option>Programming</option>
            <option>Other</option>
            </select>-->
        Category:
        <br />
        @Html.TextBoxFor(m => m.Catagory) @Html.ValidationMessageFor(m => m.Catagory)
        <br />
       
       
    </div> 
    <h2 style="text-align:center">@Session["UserId"].ToString() Profile Card</h2>

    if (@Session["UserId"].ToString() == "mahdiasali")
    {
    <div class="card">
        <img src="~/Content/electronix/images/mahdi.jpg" alt="John" style="width:100%">
        <h1>@Session["UserId"]</h1>
        <p class="title">Catagory: @Session["Catagory"]</p>
        <p>@Session["Email"]</p>
        <div style="margin: 24px 0;">
            <a href="#"><i class="fa fa-dribbble"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-facebook"></i></a>
        </div>
        <p><button>Save</button></p>

        @**<p><input id="Submit" type="submit" value="Save"></p>*@
    </div>
    }
    else if (@Session["UserId"].ToString() == "Elonav")
    {
        <div class="card">
            <img src="~/Content/electronix/images/elon.jpg" alt="John" style="width:100%">
            <h1>@Session["UserId"]</h1>
            <p class="title">Catagory: @Session["Catagory"]</p>
            <p>@Session["Email"]</p>
            <div style="margin: 24px 0;">
                <a href="#"><i class="fa fa-dribbble"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-linkedin"></i></a>
                <a href="#"><i class="fa fa-facebook"></i></a>
            </div>
            <p><button>Save</button></p>
        </div>
    }
    else
    {
        <div class="card">
            <img src="~/Content/electronix/images/facebook-avatar.jpg" alt="John" style="width:100%">
            <h1>@Session["UserId"]</h1>
            <p class="title">Catagory: @Session["Catagory"]</p>
            <p>@Session["Email"]</p>
            <div style="margin: 24px 0;">
                <a href="#"><i class="fa fa-dribbble"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-linkedin"></i></a>
                <a href="#"><i class="fa fa-facebook"></i></a>
            </div>
            <p><button>Save</button></p>
        </div>
    }
    }
</body>
</html>

PcStoreWebsite/Views/CBLogin/WrongPage.cshtml
@{
    ViewBag.Title = "WrongPage";
    Layout = "~/Views/Shared/_PcStoreLayout.cshtml";
}

<h2>Sorry, this page is not exists.</h2>